#!/usr/bin/env bash
# Run nginx as nginx user
sudo pkill -f apache2
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo chmod 644 /etc/nginx/nginx.conf
sed -i '1iuser nginx;' /etc/nginx/nginx.conf
sudo -u nginx service nginx start
